/* gp-detail.js — shared behavior for every b/<id> and p/<key> detail page
 * (generated by build.py). Makes the landing page's promises true site-wide:
 * saved Operator context (gp-ctx) rides along on every brief copy, copies can
 * be marked run (gp-runs), and per-step playbook copies fetch the brief from
 * /raw/<id>.md on demand. Everything degrades gracefully when localStorage or
 * fetch is unavailable. The Operator-context block below is byte-identical to
 * withContext() in template.html — edit them together. */
(function () {
"use strict";

function load(k, fb) {
  try {
    var v = JSON.parse(localStorage.getItem(k));
    return v === null || v === undefined ? fb : v;
  } catch (e) { return fb; }
}
function withContext(body) {
  var ctx = load("gp-ctx", {}) || {};
  var L = [];
  if (ctx.stack) L.push("- Stack: " + ctx.stack);
  if (ctx.product) L.push("- Product: " + ctx.product);
  if (ctx.stage) L.push("- Stage: " + ctx.stage);
  if (ctx.notes) L.push("- Watch out for: " + ctx.notes);
  if (!L.length) return body;
  return body + "\n\n## Operator context\nSupplied by the operator of this repo — weigh it while auditing.\n" + L.join("\n");
}
function markRun(id) {
  try {
    var runs = JSON.parse(localStorage.getItem("gp-runs") || "{}") || {};
    runs[id] = Date.now();
    localStorage.setItem("gp-runs", JSON.stringify(runs));
  } catch (e) {}
}
function hasRun(id) {
  try { return !!(JSON.parse(localStorage.getItem("gp-runs") || "{}") || {})[id]; }
  catch (e) { return false; }
}

function flash(b, m) {
  if (!b.dataset.label) b.dataset.label = b.textContent;
  clearTimeout(b._t);
  b.textContent = m; b.classList.add("done");
  b._t = setTimeout(function () { b.textContent = b.dataset.label; b.classList.remove("done"); }, 1600);
}
function copy(t, b, then) {
  function ok() { flash(b, b.classList.contains("cp") ? "✓" : "Copied ✓"); if (then) then(); }
  function fb() {
    var a = document.createElement("textarea");
    a.value = t; a.style.position = "fixed"; a.style.opacity = "0";
    document.body.appendChild(a); a.select();
    try { document.execCommand("copy"); ok(); } catch (e) { b.textContent = "copy failed"; }
    a.remove();
  }
  if (navigator.clipboard && navigator.clipboard.writeText) { navigator.clipboard.writeText(t).then(ok, fb); }
  else fb();
}

/* the landing page's post-copy hint, rebuilt here (DOM only, no innerHTML) */
var _hintT;
function showHint(output, id) {
  var el = document.getElementById("gp-hint");
  if (!el) {
    el = document.createElement("div"); el.className = "gp-hint"; el.id = "gp-hint";
    document.body.appendChild(el);
  }
  el.textContent = "";
  var b = document.createElement("b"); b.textContent = "inside your repo";
  var code = document.createElement("code"); code.textContent = output || "the report";
  el.append("Paste into Claude Code, Cursor, or any agent ", b, " — it writes ", code,
            " at the root (or in reports/).");
  if (id) {
    var mr = document.createElement("button"); mr.type = "button"; mr.className = "markrun";
    if (hasRun(id)) { mr.textContent = "✓ run"; mr.disabled = true; }
    else {
      mr.textContent = "✓ mark it run";
      mr.onclick = function () { markRun(id); mr.textContent = "✓ marked"; mr.disabled = true; };
    }
    el.append(" ", mr);
  }
  var x = document.createElement("button"); x.type = "button"; x.className = "x";
  x.textContent = "×"; x.setAttribute("aria-label", "Dismiss");
  x.onclick = function () { el.hidden = true; clearTimeout(_hintT); };
  el.append(x);
  el.hidden = false;
  clearTimeout(_hintT);
  _hintT = setTimeout(function () { el.hidden = true; }, 9000);
}

document.addEventListener("click", function (e) {
  var b = e.target.closest("[data-copy]");
  if (b) {
    var s = document.querySelector(b.getAttribute("data-copy"));
    if (!s) return;
    var txt = s.value !== undefined ? s.value : s.textContent;
    var brief = b.getAttribute("data-brief");
    if (b.hasAttribute("data-ctx")) txt = withContext(txt);
    copy(txt, b, brief ? function () { showHint(b.getAttribute("data-output"), brief); } : null);
    return;
  }
  /* per-step playbook copy: fetch the brief body on demand */
  var f = e.target.closest("[data-fetch]");
  if (!f) return;
  e.preventDefault();
  var id = f.getAttribute("data-brief");
  var out = f.getAttribute("data-output");
  if (f._body) { copy(withContext(f._body), f, function () { showHint(out, id); }); return; }
  f.textContent = "…";
  fetch(f.getAttribute("data-fetch"))
    .then(function (res) { if (!res.ok) throw new Error(res.status); return res.text(); })
    .then(function (text) {
      f._body = text.replace(/\n+$/, "");
      f.textContent = f.dataset.label || "copy";
      copy(withContext(f._body), f, function () { showHint(out, id); });
    })
    .catch(function () {
      /* graceful fallback: hand over a plain link to the raw brief */
      var a = document.createElement("a");
      a.className = f.className; a.textContent = "open raw ↗";
      a.href = f.getAttribute("data-raw") || f.getAttribute("data-fetch");
      f.replaceWith(a);
    });
});
})();
