/* goal-prompts service worker — generated by build.py; do not hand-edit.
 * Precaches the app shell + self-hosted fonts so the catalog, Studio, and
 * Vitals Viewer work offline. HTML is network-first (fresh when online,
 * cached when not); static assets are cache-first. Version is a content
 * hash, so a deploy makes a new cache and the old one is purged. */
"use strict";
var CACHE = "goal-prompts-409f0d9e17c4";
var PRECACHE = ["/", "/studio", "/vitals", "/examples/", "/manifest.json", "/tokens.css", "/bodies.json", "/js/catalog-core.js", "/js/report-parser.js", "/js/gp-detail.js", "/fonts/schibstedgrotesk-latin-var.woff2", "/fonts/plexsans-latin-400.woff2", "/fonts/plexsans-latin-600.woff2", "/fonts/plexmono-latin-400.woff2", "/fonts/plexmono-latin-600.woff2", "/icons/icon-192.png", "/icons/icon-512.png"];
self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    return Promise.all(PRECACHE.map(function (u) {
      return c.add(new Request(u, { cache: "reload" })).catch(function () {});
    }));
  }).then(function () { return self.skipWaiting(); }));
});
self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.map(function (k) { if (k !== CACHE) return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});
self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // never touch cross-origin (GitHub, analytics)
  if (url.pathname.indexOf("/raw/") === 0) return;   // raw briefs stay network-only — their fetch counts are the usage metric (docs/usage-metrics.md)
  var isHTML = req.mode === "navigate" ||
    (req.headers.get("accept") || "").indexOf("text/html") !== -1;
  if (isHTML) {
    e.respondWith(fetch(req).then(function (res) {
      var copy = res.clone();
      caches.open(CACHE).then(function (c) { c.put(req, copy); });
      return res;
    }).catch(function () {
      return caches.match(req).then(function (m) { return m || caches.match("/"); });
    }));
    return;
  }
  e.respondWith(caches.match(req).then(function (m) {
    return m || fetch(req).then(function (res) {
      if (res && res.status === 200 && res.type === "basic") {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put(req, copy); });
      }
      return res;
    }).catch(function () { return m; });
  }));
});
/* Opt-in weekly Vitals reminder (see the landing's reminder toggle). Fires only
 * when the user explicitly enabled it and the browser supports periodicSync
 * (Chromium, installed PWA) — nothing is auto-enabled and nothing leaves the
 * device.
 * R34 (RETENTION R8a): a worker can't read localStorage, so the pages mirror
 * the two fields this check needs — runs["29"] + remind.on — into IndexedDB
 * (db "gp-sw", store "kv", key "vitals"; writers: template.html's
 * mirrorVitalsState and js/gp-detail.js — keep all three in step). The
 * notification is skipped when reminders are off or Vitals ran under 7 days
 * ago; a missing mirror (an opt-in that predates it) falls back to notifying,
 * matching the old behavior rather than going silently dead. */
var VITALS_STALE_MS = 7 * 86400000;
function readVitalsState() {
  return new Promise(function (resolve) {
    var t = setTimeout(function () { resolve(null); }, 3000);
    function done(v) { clearTimeout(t); resolve(v); }
    try {
      var req = indexedDB.open("gp-sw", 1);
      req.onupgradeneeded = function () { try { req.result.createObjectStore("kv"); } catch (e) {} };
      req.onerror = function () { done(null); };
      req.onsuccess = function () {
        try {
          var db = req.result;
          var get = db.transaction("kv").objectStore("kv").get("vitals");
          get.onsuccess = function () { db.close(); done(get.result || null); };
          get.onerror = function () { db.close(); done(null); };
        } catch (e) { done(null); }
      };
    } catch (e) { done(null); }
  });
}
/* the notify decision, pure — exposed as self.gpShouldNotify so
 * tests/sw_reminder.test.cjs can exercise it without a browser */
function gpShouldNotify(state, now) {
  if (state && state.remindOn === false) return false;
  var last = (state && typeof state.runs29 === "number" && state.runs29 > 0) ? state.runs29 : 0;
  return !last || now - last >= VITALS_STALE_MS;
}
self.gpShouldNotify = gpShouldNotify;
self.addEventListener("periodicsync", function (e) {
  if (e.tag !== "vitals-weekly") return;
  e.waitUntil(readVitalsState().then(function (state) {
    if (!gpShouldNotify(state, Date.now())) return;
    /* R33 (RETENTION R6): land on the Vitals Viewer — the page that shows the
     * history this ritual accrues — instead of a cold catalog anchor. */
    return self.registration.showNotification("Weekly Vitals is due", {
      body: "Ten minutes for fresh trend arrows on your repo.",
      icon: "/icons/icon-192.png", badge: "/icons/icon-192.png",
      tag: "vitals-weekly", data: { url: "/vitals?src=reminder" }
    });
  }));
});
self.addEventListener("notificationclick", function (e) {
  e.notification.close();
  var url = (e.notification.data && e.notification.data.url) || "/";
  var bare = url.replace("?src=reminder", "");  // match open windows without the attribution query
  e.waitUntil(clients.matchAll({ type: "window" }).then(function (cs) {
    for (var i = 0; i < cs.length; i++) {
      if (cs[i].url.indexOf(bare) !== -1 && "focus" in cs[i]) {
        /* navigate the existing window so ?src=reminder rides along and the
         * page can fire reminder_return — a focus alone would hide the return.
         * If navigate() rejects, still surface the window rather than no-op. */
        if ("navigate" in cs[i]) {
          var win = cs[i];
          return win.navigate(url)
            .then(function (c) { return c ? c.focus() : win.focus(); })
            .catch(function () { return win.focus(); });
        }
        return cs[i].focus();
      }
    }
    if (clients.openWindow) return clients.openWindow(url);
  }));
});
